---
- name: Configure multiple servers
  hosts: servers
  become: yes

  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install packages
      apt:
        name:
          - vim
          - htop
          - wget
        state: present

    - name: Create a test file
      copy:
        dest: /root/test_file.txt
        content: "Configured by Ansible on {{ inventory_hostname }}"
